version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify the Node.js version you are using
    commands:
      - echo Installing dependencies...
      - npm install  # Install Node.js dependencies

  build:
    commands:
      - echo Building the backend API...
      - npm run build  # Optional: If you have a build script for your backend

  post_build:
    commands:
      - echo Backend API deployment in progress...
      # Add commands for backend deployment (e.g., Lambda deploy, API Gateway setup, etc.)

artifacts:
  files:
    - '**/*'  # Include all the source files for the backend API
    - 'package.json'  # Include package.json if necessary for Lambda deployment

cache:
  paths:
    - 'node_modules/**/*'  # Cache node_modules for faster builds
